# ================================================
# ROLE : Common
# Objectif : Installation des paquets de base
# ================================================
---

- name: Mis à jour des packges
  apt:
    update_cache: true

- name: Installation des outils de base
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - net-tools
      - vim
    state: present

- name: Création du dossier /opt/apps
  file:
    path: /opt/apps
    state: directory
    mode: '0755'

- name: Ajout de user vagrant docker
  user:
    name: vagrant
    groups: docker
    append: true

- name: Affichage du message de confirmation
  debug: 
    msg: "✅ {{ inventory_hostname }} configuré avec le role common"
