Vagrant.configure("2") do |config|
    
    # VM 1 : srv-app
    config.vm.define "app" do |app|
        app.vm.box      = "bento/ubuntu-22.04"
        app.vm.hostname = "srv-app"
        app.vm.network "private_network", ip: "192.168.56.11"

        app.vm.provider "virtualbox" do |vb|
            vb.name   = "srv-app"
            vb.memory = "1024"
            vb.cpus   = 1
        end
    end

    # VM 2 : srv-db
    config.vm.define "db" do |db|
        db.vm.box = "bento/ubuntu-22.04"
        db.vm.hostname = "srv-db"
        db.vm.network "private_network", ip: "192.168.56.12"

        db.vm.provider "virtualbox" do |vb|
        vb.name = "srv-db"
        vb.memory = "1024"
        vb.cpus = 1
        end
    end

    # VM 3 srv-ansible 192.168.56.20
    config.vm.define "ansible" do |ansible|
        ansible.vm.box = "bento/ubuntu-22.04"
        ansible.vm.hostname = "srv-ansible"
        ansible.vm.network "private_network", ip: "192.168.56.20"

        ansible.vm.provider "virtualbox" do |vb|
            vb.name   = "srv-ansible"
            vb.memory = "1024"
            vb.cpus   = 1
        end

        ansible.vm.provision "shell", inline: <<-SHELL
            apt-get update -y
            apt-get install -y ansible
            cp /vagrant/.vagrant/machines/app/virtualbox/private_key /tmp/app_key
            cp /vagrant/.vagrant/machines/db/virtualbox/private_key /tmp/db_key
            chmod 600 /tmp/app_key /tmp/db_key
            chown vagrant:vagrant /tmp/app_key /tmp/db_key # Ajout des propriétés au user vagrant

            # Lancer le playbook
            cd /vagrant && ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
        SHELL
    end  
end

