---

- name: Configuration ALL servers
  hosts: all
  become: true

  roles:
    - common

- name: Configuration srv-app
  hosts: appservers
  become: true

  roles: 
    - docker
    - nginx
    - nodejs

- name: Configuration srv-db 
  hosts: dbservers
  become: true

  roles:
    - postgresql


